library(targets)
library(tarchetypes)
library(future)
library(future.batchtools)
library(beethoven)

set_args_calc()

tar_source("inst/targets/targets_initialize.R")
tar_source("inst/targets/targets_download.R")
tar_source("inst/targets/targets_calculate.R")
tar_source("inst/targets/targets_baselearner.R")
tar_source("inst/targets/targets_metalearner.R")
tar_source("inst/targets/targets_predict.R")

# bypass option
Sys.setenv("BTV_DOWNLOAD_PASS" = "TRUE")

# bind custom built GDAL
# Users should export the right path to the GDAL library
# by export LD_LIBRARY_PATH=.... command.
.libPaths(
  c(
    "/ddn/gs1/biotools/R/lib64/R/custompkg",
    .libPaths()
  )
)

# arglist_common is generated by targets_arglist.R.
plan(
  list(
    tweak(
      future.batchtools::batchtools_slurm,
      template = "inst/targets/template_slurm.tmpl",
      resources =
        list(
          memory = 8,
          log.file = "slurm_run.log",
          ncpus = 1, partition = "geo", ntasks = 1,
          email = arglist_common$user_email,
          error.file = "slurm_error.log"
        )
    ),
    multicore
  )
)

# # invalidate any nodes older than 180 days: force running the pipeline
# tar_invalidate(any_of(tar_older(Sys.time() - as.difftime(180, units = "days"))))


# # nullify download target if bypass option is set
if (Sys.getenv("BTV_DOWNLOAD_PASS") == "TRUE") {
  target_download <- NULL
}

# targets options
# For GPU support, users should be aware of setting environment
# variables and GPU versions of the packages.
# Sys.setenv("BTV_LIBRARY_PATH") will supersede
# the NIEHS default library path.
tar_option_set(
  packages =
    c("amadeus", "chopin", "targets", "tarchetypes",
      "data.table", "sf", "terra", "exactextractr",
      "beethoven",
      #"crew", "crew.cluster", 
      "tigris", "dplyr",
      "future.batchtools", "qs", "collapse",
      "tidymodels", "tune", "rsample", "torch", "brulee",
      "glmnet", "xgboost",
      "future", "future.apply", "future.callr", "callr",
      #"sftime",
      "stars", "rlang", "parallelly"),
  library = if (Sys.getenv("BTV_LIBRARY_PATH") == "") {
    c("/ddn/gs1/biotools/R/lib64/R/custompkg", "/ddn/gs1/home/songi2/r-libs")
  } else {
    c(Sys.getenv("BTV_LIBRARY_PATH"), .libPaths())
  }
  ,
  repository = "local",
  error = "stop",
  memory = "transient",
  format = "qs",
  storage = "worker",
  deployment = "worker",
  garbage_collection = TRUE,
  seed = 202401L
)

# should run tar_make_future()

list(
  target_init,
  target_download,
  target_calculate_fit,
  target_baselearner
  #,
  # target_metalearner,
  # target_calculate_predict,
  # target_predict,
  # # documents and summary statistics
  # targets::tar_target(
  #   summary_urban_rural,
  #   summary_prediction(
  #     grid_filled,
  #     level = "point",
  #     contrast = "urbanrural"))
  # ,
  # targets::tar_target(
  #   summary_state,
  #   summary_prediction(
  #     grid_filled,
  #     level = "point",
  #     contrast = "state"
  #   )
  # )
)

# targets::tar_visnetwork(targets_only = TRUE)
# END OF FILE
