name: R Package CI

on:
  pull_request:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1  # You can change this to the R version you need

    - name: Cache C++ and R dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/R
          ~/.local/share/R
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          dependencies-${{ runner.os }}-

    - name: Install dependencies for covr and testthat
      run: R -e 'install.packages(c("covr", "testthat"), dependencies = TRUE)'

    - name: Run tests and calculate coverage
      run: |
        echo "Current working directory: $(pwd)"
        R -e 'library(covr); covr::package_coverage(coverage_file = "coverage.xml")'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        coverage_reports: ${{ github.workspace }}/coverage.xml
