on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    # Add a caching step
    steps:
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/R-${{ matrix.config.r }}/Library
          key: R-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}
        if: runner.os == 'Linux'
      
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package

      - name: Upload coverage to Codecov
        run: |
          Rscript -e "covr::codecov(token = Sys.getenv('CODECOV_TOKEN'))"
