name: test-coverage

on:
  pull_request:
    branches: [main, master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1  # You can change this to the R version you need

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run tests and calculate coverage
        run: |
          R -e 'library(covr); covr::package_coverage(quiet = FALSE)'
        shell: Rscript {0}

      - name: Generate comprehensive coverage report
        run: |
          R -e 'library(covr); covr::report(coverage_file = "coverage.xml")'
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          coverage_reports: coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-test-results
          path: test-results.txt
